interface Language {
  value: string;
  label: string;
  locale: string;
  direction: 'ltr' | 'rtl';
  dateTimeFormat: Intl.DateTimeFormatOptions;
  flag: string;
}

export const languages: Language[] = [
  {
    value: 'en',
    label: 'English',
    locale: 'en-US',
    direction: 'ltr',
    dateTimeFormat: {
      year: 'numeric',
      month: '2-digit',
      day: '2-digit',
      hour: '2-digit',
      minute: '2-digit',
      second: '2-digit',
      hour12: true,
    },
    flag: '🇺🇸'
  },
  {
    value: 'pt',
    label: 'Português',
    locale: 'pt-BR',
    direction: 'ltr',
    dateTimeFormat: {
      year: 'numeric',
      month: '2-digit',
      day: '2-digit',
      hour: '2-digit',
      minute: '2-digit',
      second: '2-digit',
      hour12: false,
    },
    flag: '🇧🇷'
  },
  {
    value: 'es',
    label: 'Español',
    locale: 'es-ES',
    direction: 'ltr',
    dateTimeFormat: {
      year: 'numeric',
      month: '2-digit',
      day: '2-digit',
      hour: '2-digit',
      minute: '2-digit',
      second: '2-digit',
      hour12: false,
    },
    flag: '🇪🇸'
  },
  {
    value: 'fr',
    label: 'Français',
    locale: 'fr-FR',
    direction: 'ltr',
    dateTimeFormat: {
      year: 'numeric',
      month: '2-digit',
      day: '2-digit',
      hour: '2-digit',
      minute: '2-digit',
      second: '2-digit',
      hour12: false,
    },
    flag: '🇫🇷'
  },
  {
    value: 'de',
    label: 'Deutsch',
    locale: 'de-DE',
    direction: 'ltr',
    dateTimeFormat: {
      year: 'numeric',
      month: '2-digit',
      day: '2-digit',
      hour: '2-digit',
      minute: '2-digit',
      second: '2-digit',
      hour12: false,
    },
    flag: '🇩🇪'
  },
  {
    value: 'ar',
    label: 'العربية',
    locale: 'ar-SA',
    direction: 'rtl',
    dateTimeFormat: {
      year: 'numeric',
      month: '2-digit',
      day: '2-digit',
      hour: '2-digit',
      minute: '2-digit',
      second: '2-digit',
      hour12: true,
    },
    flag: '🇸🇦'
  },
];

export const getEnterButtonText = (langCode: string) => {
  const texts: { [key: string]: string } = {
    en: 'Enter',
    pt: 'Entrar',
    es: 'Entrar',
    fr: 'Entrer',
    de: 'Eingeben',
    ar: 'دخول',
  };
  return texts[langCode] || 'Enter';
};

export const getTranslations = (langCode: string) => {
  const translations: { [key: string]: { [key: string]: string } } = {
    en: {
      userInfo: 'User Information',
      systemInfo: 'System Information',
      displayInfo: 'Display Information',
      locationInfo: 'Location Information',
      otherInfo: 'Other Information',
      fullUserAgent: 'Full User Agent',
      os: 'Operating System',
      browser: 'Browser',
      platform: 'Platform',
      cpuCores: 'CPU Cores',
      ram: 'RAM',
      screenSize: 'Screen Size',
      colorDepth: 'Color Depth',
      pixelRatio: 'Pixel Ratio',
      location: 'Location',
      ip: 'IP Address',
      language: 'Language',
      timezone: 'Timezone',
      datetime: 'Date and Time',
      touchSupport: 'Touch Support',
      cookiesEnabled: 'Cookies Enabled',
      doNotTrack: 'Do Not Track',
      yes: 'Yes',
      no: 'No',
      notSet: 'Not Set',
      selectedLanguage: 'Selected Language',
      backButton: 'Back',
    },
    pt: {
      userInfo: 'Informações do Usuário',
      systemInfo: 'Informações do Sistema',
      displayInfo: 'Informações de Exibição',
      locationInfo: 'Informações de Localização',
      otherInfo: 'Outras Informações',
      fullUserAgent: 'User Agent Completo',
      os: 'Sistema Operacional',
      browser: 'Navegador',
      platform: 'Plataforma',
      cpuCores: 'Núcleos de CPU',
      ram: 'Memória RAM',
      screenSize: 'Tamanho da Tela',
      colorDepth: 'Profundidade de Cor',
      pixelRatio: 'Razão de Pixels',
      location: 'Localização',
      ip: 'Endereço IP',
      language: 'Idioma',
      timezone: 'Fuso Horário',
      datetime: 'Data e Hora',
      touchSupport: 'Suporte a Toque',
      cookiesEnabled: 'Cookies Habilitados',
      doNotTrack: 'Não Rastrear',
      yes: 'Sim',
      no: 'Não',
      notSet: 'Não Definido',
      selectedLanguage: 'Idioma Selecionado',
      backButton: 'Voltar',
    },
    es: {
      userInfo: 'Información del Usuario',
      systemInfo: 'Información del Sistema',
      displayInfo: 'Información de Pantalla',
      locationInfo: 'Información de Ubicación',
      otherInfo: 'Otra Información',
      fullUserAgent: 'User Agent Completo',
      os: 'Sistema Operativo',
      browser: 'Navegador',
      platform: 'Plataforma',
      cpuCores: 'Núcleos de CPU',
      ram: 'Memoria RAM',
      screenSize: 'Tamaño de Pantalla',
      colorDepth: 'Profundidad de Color',
      pixelRatio: 'Relación de Píxeles',
      location: 'Ubicación',
      ip: 'Dirección IP',
      language: 'Idioma',
      timezone: 'Zona Horaria',
      datetime: 'Fecha y Hora',
      touchSupport: 'Soporte Táctil',
      cookiesEnabled: 'Cookies Habilitadas',
      doNotTrack: 'No Rastrear',
      yes: 'Sí',
      no: 'No',
      notSet: 'No Establecido',
      selectedLanguage: 'Idioma Seleccionado',
      backButton: 'Volver',
    },
    fr: {
      userInfo: 'Informations Utilisateur',
      systemInfo: 'Informations Système',
      displayInfo: 'Informations d\'Affichage',
      locationInfo: 'Informations de Localisation',
      otherInfo: 'Autres Informations',
      fullUserAgent: 'User Agent Complet',
      os: 'Système d\'Exploitation',
      browser: 'Navigateur',
      platform: 'Plateforme',
      cpuCores: 'Cœurs CPU',
      ram: 'Mémoire RAM',
      screenSize: 'Taille d\'Écran',
      colorDepth: 'Profondeur de Couleur',
      pixelRatio: 'Ratio de Pixels',
      location: 'Emplacement',
      ip: 'Adresse IP',
      language: 'Langue',
      timezone: 'Fuseau Horaire',
      datetime: 'Date et Heure',
      touchSupport: 'Support Tactile',
      cookiesEnabled: 'Cookies Activés',
      doNotTrack: 'Ne Pas Suivre',
      yes: 'Oui',
      no: 'Non',
      notSet: 'Non Défini',
      selectedLanguage: 'Langue Sélectionnée',
      backButton: 'Retour',
    },
    de: {
      userInfo: 'Benutzerinformationen',
      systemInfo: 'Systeminformationen',
      displayInfo: 'Anzeigeninformationen',
      locationInfo: 'Standortinformationen',
      otherInfo: 'Weitere Informationen',
      fullUserAgent: 'Vollständiger User Agent',
      os: 'Betriebssystem',
      browser: 'Browser',
      platform: 'Plattform',
      cpuCores: 'CPU-Kerne',
      ram: 'Arbeitsspeicher',
      screenSize: 'Bildschirmgröße',
      colorDepth: 'Farbtiefe',
      pixelRatio: 'Pixelverhältnis',
      location: 'Standort',
      ip: 'IP-Adresse',
      language: 'Sprache',
      timezone: 'Zeitzone',
      datetime: 'Datum und Uhrzeit',
      touchSupport: 'Touch-Unterstützung',
      cookiesEnabled: 'Cookies Aktiviert',
      doNotTrack: 'Nicht Verfolgen',
      yes: 'Ja',
      no: 'Nein',
      notSet: 'Nicht Festgelegt',
      selectedLanguage: 'Ausgewählte Sprache',
      backButton: 'Zurück',
    },
    ar: {
      userInfo: 'معلومات المستخدم',
      systemInfo: 'معلومات النظام',
      displayInfo: 'معلومات العرض',
      locationInfo: 'معلومات الموقع',
      otherInfo: 'معلومات أخرى',
      fullUserAgent: 'وكيل المستخدم الكامل',
      os: 'نظام التشغيل',
      browser: 'المتصفح',
      platform: 'المنصة',
      cpuCores: 'أنوية المعالج',
      ram: 'الذاكرة العشوائية',
      screenSize: 'حجم الشاشة',
      colorDepth: 'عمق الألوان',
      pixelRatio: 'نسبة البكسل',
      location: 'الموقع',
      ip: 'عنوان IP',
      language: 'اللغة',
      timezone: 'المنطقة الزمنية',
      datetime: 'التاريخ والوقت',
      touchSupport: 'دعم اللمس',
      cookiesEnabled: 'ملفات تعريف الارتباط مفعلة',
      doNotTrack: 'عدم التتبع',
      yes: 'نعم',
      no: 'لا',
      notSet: 'غير محدد',
      selectedLanguage: 'اللغة المختارة',
      backButton: 'رجوع',
    },
  };
  return translations[langCode] || translations['en'];
};